---
name: My Badges

on:
  workflow_dispatch:
  schedule:
    - cron: "18 23 * * *"

permissions:
  contents: write

jobs:
  my-badges:
    runs-on: ubuntu-24.04
    steps:
      - name: Update My Badges
        run: npx update-my-badges ${{ github.repository_owner }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
